---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/

    - /usr/bin/rsync -av --delete --exclude='.git*' ./ $DEPLOYPATH || (/bin/cp -R * $DEPLOYPATH && /bin/cp .htaccess $DEPLOYPATH && /bin/cp robots.txt $DEPLOYPATH)